jobs:
- job: 'build'
  pool: 'Win-CPU-2019'
  strategy:
    maxParallel: 2
    matrix:
      debug:
        BuildConfig: 'Debug'
  variables:
    OrtPackageId: 'Microsoft.ML.OnnxRuntime'
    MsbuildArguments: '-detailedsummary -maxcpucount -consoleloggerparameters:PerformanceSummary'
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    EnvSetupScript: setup_env.bat
    buildArch: x64
    setVcvars: true
    ALLOW_RELEASED_ONNX_OPSET_ONLY: '0'
  timeoutInMinutes: 120
  workspace:
    clean: all
  steps:    
  - task: UsePythonVersion@0
    inputs: 
      versionSpec: '3.7' 
      addToPath: true 
      architecture: $(buildArch)

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - task: BatchScript@1
    displayName: 'setup env'
    inputs:
      filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\$(EnvSetupScript)'
      modifyEnvironment: true
      workingFolder: '$(Build.BinariesDirectory)'


  - task: PythonScript@0
    displayName: 'Regenerate cmake config with STATIC_ANALYSIS=ON '
    condition: and(succeeded(), eq(variables['BuildConfig'], 'Debug'))
    inputs:
      scriptPath: '$(Build.SourcesDirectory)\tools\ci_build\build.py'
      arguments: '--config Debug --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --build_shared_lib --update --cmake_generator "Visual Studio 16 2019" --build_wheel --build_shared_lib --enable_onnx_tests --cmake_extra_defines onnxruntime_ENABLE_STATIC_ANALYSIS=ON'
      workingDirectory: '$(Build.BinariesDirectory)'

      
  #Manually set msBuildCommandline so that we can also set CAExcludePath
  - task: SDLNativeRules@2
    displayName: 'Run the PREfast SDL Native Rules for MSBuild'
    condition: and(succeeded(), eq(variables['BuildConfig'], 'Debug'))
    inputs:
      userProvideBuildInfo: msBuildInfo
      msBuildVersion: 16.0
      msBuildArchitecture: x64
      msBuildCommandline: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "$(Build.BinariesDirectory)\Debug\onnxruntime.sln" /p:platform=x64 /p:configuration="Debug" /p:CAExcludePath="$(Build.BinariesDirectory);$(Build.SourcesDirectory)\cmake;C:\program files (x86)" /p:VisualStudioVersion="16.0" /m /p:PreferredToolArchitecture=x64'
    continueOnError: true 


  - task: PostAnalysis@2
    displayName: 'Post Analysis'
    inputs:
      GdnBreakAllTools: false
      GdnBreakGdnToolSDLNativeRules: true
      GdnBreakGdnToolSDLNativeRulesSeverity: Warning

  - task: PublishTestResults@2
    displayName: 'Publish unit test results'
    inputs:
      testResultsFiles: '**/*.results.xml'
      searchFolder: '$(Build.BinariesDirectory)'
      testRunTitle: 'Unit Test Run'
    condition: succeededOrFailed()

  - template: templates/component-governance-component-detection-steps.yml
    parameters :
      condition : 'succeeded'

